version: "3"
services:
  app:
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    restart: always
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=heslo
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    ports:
      - "8080:8080"